version: '3.7'

services:

    users:
        build:
            context: ./services/users
            dockerfile: Dockerfile-prod
        environment:
            - FLASK_ENV=production
            - APP_SETTINGS=project.config.ProductionConfig
            - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
            - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
            - SECRET_KEY=${SECRET_KEY}
            - TOKEN_EXPIRATION_DAYS=30
            - TOKEN_EXPIRATION_SECONDS=0
        depends_on:
            - users-db
        expose:
            - 5000

    users-db:
        build:
            context: ./services/users/project/db
            dockerfile: Dockerfile
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    client:
        container_name: client
        build:
            context: ./services/client
            dockerfile: Dockerfile-prod
            args:
                - NODE_ENV=production
                - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
        ports:
            - '3007:80'
        depends_on:
            - users

    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile-prod
        restart: always
        ports:
            - 80:80
        depends_on:
            - users
            - client

