"""empty message

Revision ID: 9da94ed38bf4
Revises: e4e6e54937bb
Create Date: 2019-06-08 18:05:21.163631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9da94ed38bf4"
down_revision = "e4e6e54937bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("admin", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET admin=False")
    op.alter_column("users", "admin", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "admin")
    # ### end Alembic commands ###
